export const ActionTypes = {
    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    SET_PRODUCTS: 'SET_PRODUCTS',
    FETCH_PRODUCT_DETAILS: 'FETCH_PRODUCT_DETAILS',
    SET_PRODUCT_DETAILS: 'SET_PRODUCT_DETAILS',
    FETCH_PRODUCT_CATEGORIES: 'FETCH_PRODUCT_CATEGORIES',
    SET_PRODUCT_CATEGORIES: 'SET_PRODUCT_CATEGORIES',
    IS_FETCHING : 'IS_FETCHING',
    FETCH_CATEGORY_LIST : 'FETCH_CATEGORY_LIST',
    SET_CATEGORY_LIST : 'SET_CATEGORY_LIST',
};